name: publish

on: [push, pull_request]

jobs:
  check:
    if: (github.event_name == 'pull_request') || (github.event.ref_type == 'tag')
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Provision virtual environment and run tests
        run: pip install nox wheel && nox -s sanka-venv-3.9


  publish:
    if: (github.event_name == 'pull_request') || (github.event.ref_type == 'tag')
    needs: check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Provision virtual environment and run tests
        run: pip install nox wheel && nox

      - name: Build distribution ðŸ“¦
        run: nox -s build-sanka

      - name: Publish distribution ðŸ“¦ to Test PyPI
        if: github.event.pull_request.merged == true
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.test_pypi_password }}
          repository_url: https://test.pypi.org/legacy/

      - name: Publish distribution ðŸ“¦ to PyPI
        if: github.event.ref_type == 'tag'
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.pypi_password }}

